app/__init__.py
"""
WELCOME: app constructor & factory - glave/app/__init__.py
"""
from flask import Flask, render_template, current_app
from werkzeug.local import LocalProxy

from .extensions import mail, ckeditor, moment, csrf

# relay for logger
logger = LocalProxy(lambda: current_app.logger)


def crash_page(e):
    return render_template('error_pages/500.html'), 500

def page_not_found(e):
    return render_template('error_pages/404.html'), 404

def page_forbidden(e):
    return render_template('error_pages/403.html'), 403

# sort of like an application factory
def create_app(*args): 
    # Initialize Flask and set some config values
    app = Flask(__name__)
    app.config.from_object('settings')
    
    mail.init_app(app)
    ckeditor.init_app(app)
    moment.init_app(app)
    csrf.init_app(app)

    '''
    if os.environ.get('FLASK_ENV', False) != 'development':
        sentry_sdk.init(dsn="", \
                        integrations=[FlaskIntegration()])
    '''

    # BLUEPRINTS
    from .views import views as views_blueprint
    app.register_blueprint(views_blueprint)
    

    '''
    # Callback function to check if a JWT exists in the redis blocklist
    @jwt.token_in_blocklist_loader
    def check_if_token_is_revoked(jwt_header, jwt_payload):
        jti = jwt_payload["jti"]
        return models.RevokedTokenModel.is_jti_blocklisted(jti) 
    '''
    
    # error handlers
    app.register_error_handler(500, crash_page)
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(403, page_forbidden)


    # Executes before the first request is processed.
    @app.before_first_request
    def before_first_request():
        pass


    @app.before_request
    def before_request():
        pass
    
    return app

app/views/__init__.py
"""
WELCOME

"""
from flask import Blueprint

views = Blueprint('views', __name__)

from . import basics

app/views/basics.py
"""
WELCOME
"""
from flask import render_template, redirect, flash, url_for, abort, request, send_from_directory, current_app
from flask_mail import Message
from slugify import slugify

# our objects
from . import views


######################
#### STATIC PAGES ####
######################
# Displays the home page.
@views.route('/')
@views.route('/index')
@views.route('/index.html')
# Users must be authenticated to view the home page, but they don't have to have any particular role.
# Flask-Security will display a login form if the user isn't already authenticated.
def index():
    return render_template('pages/index.html')


@views.route('/about.html')
def about():
    return render_template('pages/about.html')

@views.route('/baby.html')
def baby():
    return render_template('pages/baby.html')

@views.route('/birthday.html')
def birthday():
    return render_template('pages/birthday.html')

@views.route('/bisque.html')
def bisque():
    return render_template('pages/bisque.html')

@views.route('/bridal.html')
def bridal():
    return render_template('pages/bridal.html')  

@views.route('/clay.html')
def clay():
    return render_template('pages/clay.html')

@views.route('/clayc.html')
def clayc():
    return render_template('pages/clayc.html')  

@views.route('/corporate.html')
def corporate():
    return render_template('pages/corporate.html')

@views.route('/fairy.html')
def fairy():
    return render_template('pages/fairy.html')

@views.route('/glass.html')
def glass():
    return render_template('pages/glass.html')

@views.route('/hours.html')
def hours():
    return render_template('pages/hours.html')

@views.route('/mobile.html')
def mobile():
    return render_template('pages/mobile.html')

@views.route('/party.html')
def party():
    return render_template('pages/party.html')

@views.route('/peace.html')
def peace():
    return render_template('pages/peace.html')

@views.route('/project.html')
def project():
    return render_template('pages/project.html')

@views.route('/rent.html')
def rent():
    return render_template('pages/rent.html')
@views.route('/summer.html')
def summer():
    return render_template('pages/summer.html')

app/templates/base.html
{# ------------------ BASE! ---------------- #}
{# pretty much every page will use this stuff #}

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
  {# check out the templates/shared/_head.html to see CSS and head includes #}
  {% include "shared/_head.html" %}
    <body class="stretched">

        <!-- Document Wrapper
        ============================================= -->
        <div id="wrapper" class="clearfix">
        
          {% if not disable_navbar %}
            {% include "shared/_nav.html" with context %}
          {% endif%}
          
          {% block content %}
          <!-- Begin Page Content -->
          <div class="container-fluid">
            
          </div>
          {% endblock %}
      
          
        </div>
        {#-- End of Main Content --#}

        {% include "shared/_footer.html" with context %}

      </div>
      <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper --> 

    {% block btt %}
      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>
    {% endblock %}

    {# You can put modals pretty much anywhere, but some folks find it tidy to keep them out of the content block #}
    {% block modals %}{% endblock %}

    {# LOAD UP ALL YOUR THEME'S JS HERE #}
    {% include "shared/_js.html" with context %}

    {# A convenient block so you can drop in your own template-specific JS code #}
    {% block tail %}{% endblock %}

    {# activate menu items #}
    <script>
      $('#{% block linkitem %}replaceme{% endblock %}').addClass('active');
    </script>
  </body>
</html>        

app/templates/pages/baby.html
{% extends "base.html" %}

{% block content %}

    <!-- Slider
    ============================================= -->
    <section id="slider" class="slider-element slider-parallax swiper_wrapper min-vh-60 min-vh-md-100 include-header" data-loop="true">

        <div class="slider-inner">
            <div class="swiper-container swiper-parent">
                <div class="swiper-wrapper">
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary not" id="picture2">Baby Fun</h2>
                                    <p class="fw-light font-primary d-none d-sm-block" id="picture2">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/baby/1.jpg') }}');"></div>
                    </div>
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary">Baby Fun</h2>
                                    <p class="fw-light font-primary d-none d-sm-block">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/baby/2.jpg') }}');"></div>
                    </div>
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary">Baby Fun</h2>
                                    <p class="fw-light font-primary d-none d-sm-block">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/baby/4.jpg') }}');"></div>
                    </div>
                </div>
                <!-- Slider Arrows
                ============================================= -->
                <div class="slider-arrow-left" class="bg-transparent"><i class="icon-line-arrow-left"></i></div>
                <div class="slider-arrow-right" class="bg-transparent"><i class="icon-line-arrow-right"></i></div>
            </div>

            <!-- Slider Mouse Icon
            ============================================= -->
            <a href="#" data-scrollto="#content" data-offset="0" class="dark one-page-arrow"><img class="infinite animated fadeInDown" src="{{ url_for('static', filename='demos/business/images/mouse.svg') }}" alt="Image" ></a>
        </div>

    </section>

    <!-- Content
    ============================================= -->
    <section id="content">

        <div class="content-wrap pb-0" style="z-index: 1;">

            <div class="container topmargin clearfix">

                <!-- What We Do
                ============================================= -->
                <div class="heading-block center border-0" data-heading="B">
                    <h3>It’s Baby Time!</h3>
                </div>
                <div class="row clearfix">
                    <div class="center col-lg-8 offset-lg-2 bottommargin">
                        <h3 class="text-rotater font-secondary" data-separator="," data-rotate="fadeInRight" data-speed="3500">Babies can get involved, too!  Your baby’s handprints and/or footprints on a mug, plate, or platter look so great. The paints are lead-free and non-toxic, so they’re safe for your children. First, we paint their hand and press it down on the piece. If it doesn’t turn out the way you want, we can wash it off and start again!  At six months, you can do another type of project. Hand and/or foot imprints in clay.  This requires a reservation and the pick-up time is longer, but the memory is everlasting.<br>You may serve beverages, including wine or champagne to add to the ambiance of the day or evening. We will work with your catering service and help with the set-up for your special gathering. Call the studio to make a reservation.</h3>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- #content end -->

{% endblock %}

app/templates/pages/project.html
{% extends "base.html" %}

{% block content %}

    <!-- Slider
    ============================================= -->
    <section id="slider" class="slider-element slider-parallax swiper_wrapper min-vh-60 min-vh-md-100 include-header" data-loop="true">

        <div class="slider-inner">
            <div class="swiper-container swiper-parent">
                <div class="swiper-wrapper">
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary not">Projects</h2>
                                    <p class="fw-light font-primary d-none d-sm-block">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/slider/6.jpg') }}');"></div>
                    </div>
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary">Projects</h2>
                                    <p class="fw-light font-primary d-none d-sm-block">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/project/8.jpg') }}');"></div>
                    </div>
                    <div class="swiper-slide dark">
                        <div class="container">
                            <div class="slider-caption slider-caption-center">
                                <div>
                                    <h2 class="font-primary">Projects</h2>
                                    <p class="fw-light font-primary d-none d-sm-block">Your Own Pottery And Glass Fusing Art Studio</p>
                                    <a href="{{ url_for ('views.project') }}" class="button button-rounded button-large nott ls0 font-primary">Get Started</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide-bg" style="background-image: url('{{ url_for('static', filename='img/slider/7.jpg') }}');"></div>
                    </div>
                </div>
                <!-- Slider Arrows
                ============================================= -->
                <div class="slider-arrow-left" class="bg-transparent"><i class="icon-line-arrow-left"></i></div>
                <div class="slider-arrow-right" class="bg-transparent"><i class="icon-line-arrow-right"></i></div>
            </div>

            <!-- Slider Mouse Icon
            ============================================= -->
            <a href="#" data-scrollto="#content" data-offset="0" class="dark one-page-arrow"><img class="infinite animated fadeInDown" src="{{ url_for('static', filename='demos/business/images/mouse.svg') }}" alt="Image" ></a>
        </div>

    </section>

    <!-- Content
    ============================================= -->
    <section id="content">

        <div class="content-wrap pb-0" style="z-index: 1;">

            <div class="container topmargin clearfix">

                <!-- What We Do
                ============================================= -->
                <div class="heading-block center border-0" >
                    <h3>Pick Your Project</h3>
                </div>
                <div class="row clearfix">

                    <div class="clear"></div>

                    <!-- Features colomns
                    ============================================= -->
                    <div class="row clearfix">
                        <div class="col-lg-4 bottommargin-sm">
                            <div class="feature-box media-box fbox-bg">
                                <div class="fbox-media">
                                    <a href="{{url_for('views.clay')}}"><img src="{{ url_for('static', filename='img/project/4.jpg') }}" alt="Featured Box Image"></a>
                                </div>
                                <div class="fbox-content fbox-content-lg">
                                    <h3 class="nott ls0 fw-semibold">Clay<span class="subtitle font-secondary fw-light ls0">Come play in the mud!  Hand-built projects can be treasured for a lifetime!  You do not need a license to get behind the wheel at Spirit of Clay.</span></h3>
                                    <a href="{{url_for('views.clay')}}" class="button-link border-0 color">Find Out More</a>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 bottommargin-sm">
                            <div class="feature-box media-box fbox-bg">
                                <div class="fbox-media">
                                    <a href="#"><img src="{{ url_for('static', filename='img/project/5.jpg') }}" alt="Featured Box Image"></a>
                                </div>
                                <div class="fbox-content fbox-content-lg">
                                    <h3 class="nott ls0 fw-semibold">Glass Fusing<span class="subtitle font-secondary fw-light ls0">Come make beautiful glass pieces that will be treasured forever!  We show you how to safely cut the glass, so you can have a safe and fun time!</span></h3>
                                    <a href="{{url_for('views.glass')}}" class="button-link border-0 color">Find Out More</a>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 bottommargin-sm">
                            <div class="feature-box media-box fbox-bg">
                                <div class="fbox-media">
                                    <a href="#"><img src="{{ url_for('static', filename='img/project/6.jpg') }}" alt="Featured Box Image"></a>
                                </div>
                                <div class="fbox-content fbox-content-lg">
                                    <h3 class="nott ls0 fw-semibold">Bisque<span class="subtitle font-secondary fw-light ls0">Come paint with us.  No added studio fee!  We provide everything you will need ... easy as 1, 2, 3!  We have a large selection of pieces for you to paint</span></h3>
                                    <a href="{{url_for('views.bisque')}}" class="button-link border-0 color">Find Out More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- #content end -->

{% endblock %}

app/templates/shared/_footer.html
<!-- Footer
============================================= -->
<footer id="footer" class="border-0" style="padding: 30px 0; background-color: #FFF">
    <div class="container clearfix">
        <!-- Footer Widgets
        ============================================= -->
        <div class="footer-widgets-wrap">
            <div class="row col-mb-50">
              <div class="col-md-4">
                <img src="{{url_for('static', filename='img/14.jpg')}}" style="margin-bottom: 50px" >
              </div>
              <div class="col-md-4">
                <img src="{{url_for('static', filename='img/16.jpg')}}" style="margin-bottom: 50px">
              </div>
              <div class="col-md-4">
                <img src="{{url_for('static', filename='img/17.jpg')}}" style="margin-bottom: 50px">
              </div>
            </div>  
            
            <div class="row col-mb-50">
                <div class="col-md-3">
                    <img src="{{ url_for('static', filename='img/logo1.png') }}" alt="Image" height="100" style="margin-top: -30px">
                </div>

                <div class="col-md-9">

                    <div class="row col-mb-30">
                        <div class="col-sm-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon clearfix">
                                <h4>Projects</h4>
                                <ul>
                                    <li><a href="{{url_for('views.bisque')}}">Bisque</a></li>
                                    <li><a href="{{url_for('views.clay')}}">Clay</a></li>
                                    <li><a href="{{url_for('views.glass')}}">Glass</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon clearfix">
                                <h4>Classes and Workshops</h4>
                                <ul>
                                    <li><a href="{{url_for('views.fairy')}}">Fairy Houses</a></li>
                                    <li><a href="{{url_for('views.clayc')}}">Clay Classes</a></li>
                                    <li><a href="{{url_for('views.peace')}}">Glass Fusing Clases</a></li>
                                    <li><a href="{{url_for('views.summer')}}">Summer Workshops</a></li>
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon clearfix">
                                <h4>Parties</h4>
                                <ul>
                                    <li><a href="{{url_for('views.birthday')}}">Birthday Parties</a></li>
                                    <li><a href="{{url_for('views.bridal')}}">Bridal Parties</a></li>
                                    <li><a href="{{url_for('views.baby')}}">Baby Parties</a></li>
                                    <li><a href="{{url_for('views.corporate')}}">Corporate Events</a></li>
                                    <li><a href="{{url_for('views.party')}}">Party Pail</a></li>
                                    <li><a href="{{url_for('views.rent')}}">Rent the Studio</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon clearfix">
                                <h4>Contact Us</h4>
                                <ul>
                                    <li><a href="#">(440) - 684 - 0001</a></li>
                                    <li><a href="#">828 Som Center Rd, Mayfield Village, OH 44143</a></li>
                                    <li><a href="#">spiritofclay@sbcgobal.net</a></li>
                                    <li><a href="https://www.facebook.com/pages/category/Arts---Crafts-Store/Spirit-of-Clay-114626395218961/" target="_blank">Facebook</a></li>
                                    <li><a href="https://www.instagram.com/spiritofclay/?hl=en" target="_blank">Instagram</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="line line-sm"></div>

                    <div class="row justify-content-between col-mb-30">
                        <div class="col-12 col-md-auto text-center text-md-start">
                            <small class="fw-light" style="color: #AAA"> &copy; 2020 Spirit Of Clay. All Rights Reserved.  Made by students at Gilmour Academy</small>
                        </div>

                        <div class="col-12 col-md-auto text-center text-md-end">
                            <a href="https://www.facebook.com/pages/category/Arts---Crafts-Store/Spirit-of-Clay-114626395218961/" target="_blank" class="social-icon inline-block si-mini si-rounded si-colored si-facebook">
                                <i class="icon-facebook"></i>
                                <i class="icon-facebook"></i>
                            </a>

                            <a href="https://www.instagram.com/spiritofclay/?hl=en" target="_blank" class="social-icon inline-block si-mini si-rounded si-colored si-instagram">
                                <i class="icon-instagram"></i>
                                <i class="icon-instagram"></i>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</footer><!-- #footer end -->

app/templates/shared/_head.html
<head>
 
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,600,700|Open+Sans:300,400,600,700,800,900&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/dark.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/swiper.css') }}" type="text/css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" type="text/css" />

	<!-- Business Demo Specific Stylesheet -->
	<link rel="stylesheet" href="{{ url_for('static', filename='demos/business/business.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='demos/business/css/fonts.css') }}" type="text/css" />
	<!-- / -->

	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-icons.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}" type="text/css" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}" type="text/css" />

	<link rel="stylesheet" href="{{ url_for('static', filename='one-page/css/et-line.css') }}" type="text/css" />

	<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- Theme Color
	============================================= -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/colors.php', color='00BED7') }}" type="text/css" />

	<!-- Document Title
	============================================= -->
	<title>Spirit of Clay</title>
    <link rel="icon" 
      type="image/png" 
      href="{{ url_for('static', filename='img/logo1.png') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&family=Roboto:wght@300&display=swap" rel="stylesheet">
</head>

app/templates/shared/_nav.html
<!-- Header
============================================= -->
<header id="header" class="full-header transparent-header dark header-size-md" data-sticky-class="not-dark" data-responsive-class="not-dark" data-sticky-offset="full" data-sticky-offset-negative="80">
    <div id="header-wrap">
        <div class="container">
            <div class="header-row">

                <!-- Logo
                ============================================= -->
                <div id="logo">
                    <a href="index.html" class="standard-logo" data-dark-logo="{{ url_for('static', filename='img/logo3.png') }}"><img src="{{ url_for('static', filename='img/logo3.png') }}" alt="Spirit of Clay Logo"></a>
                    <a href="index.html" class="retina-logo" data-dark-logo="{{ url_for('static', filename='img/logo3.png') }}">
                    <img src="{{ url_for('static', filename='img/logo3.png') }}" alt="Spirit of Clay Logo"></a>
                </div><!-- #logo end -->

               

                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <nav class="primary-menu not-dark">

                    <ul class="menu-container">
                        <li class="menu-item active"><a class="menu-link1" href="{{ url_for('views.about') }}"><div>About Us</div></a></li>
                        <li class="menu-item active"><a class="menu-link2" href="{{ url_for('views.hours') }}"><div>Weekly Hours</div></a></li>
                        <li class="menu-item"><a class="menu-link3" href="{{ url_for('views.project') }}"><div>Projects</div></a>
                            <ul class="sub-menu-container">
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.bisque') }}"><div>Bisque</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.clay') }}"><div>Clay</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.glass') }}"><div>Glass Fusing</div></a></li>
                            </ul>
                        </li>
                        <li class="menu-item"><a class="menu-link4" href="#"><div>Classes and Workshops</div></a>
                            <ul class="sub-menu-container">
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.fairy') }}"><div>Houses</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.clayc') }}"><div>Clay Classes</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.peace') }}"><div>Glass Fusing Classes</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.summer') }}"><div>Summer Workshops</div></a></li>
                            </ul>
                        </li>
                        <li class="menu-item"><a class="menu-link5" href="#"><div>Parties</div></a>
                            <ul class="sub-menu-container">
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.birthday') }}"><div>Birthday</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.bridal') }}"><div>Bridal</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.baby') }}"><div>Baby</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.corporate') }}"><div>Corporate Events</div></a></li>
                                <li class="menu-item"><a class="menu-link" href="{{ url_for('views.rent') }}"><div>Rent the Studio</div></a></li>
                            </ul>
                        </li>
                        <li class="menu-item"><a class="menu-link6" href="{{ url_for('views.mobile') }}"><div>Mobile Studio</div></a></li>
                    </ul>

                </nav><!-- #primary-menu end -->

                <form class="top-search-form" action="search.html" method="get">
                    <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.." autocomplete="off">
                </form>

            </div>
        </div>
    </div>
    <div class="header-wrap-clone"></div>
</header><!-- #header end -->